services:
  # PostgreSQL service for local development
  postgres-docker-php:
    image: postgres:13
    ports:
      - "5433:5432"
    env_file:
      - php/.env.docker
    environment:
      - ENVIRONMENT=docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network

  # PHP Application service for local development
  app-docker-php:
    build: php/.
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres-docker-php
    env_file:
      - php/.env.docker
    environment:
      - ENVIRONMENT=docker
    networks:
      - internal-network
    command: sh -c "chown -R www-data:www-data /var/www/html/uploads && chmod -R 755 /var/www/html/uploads && apache2-foreground"

volumes:
  postgres_data:

networks:
  internal-network:
    driver: bridge
